# docker-composeの書式のバージョン
version: '3'

services:
  api:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3000:3000
    # コンテナの作成順序
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:16
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      # MYSQL_ROOT_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # (左)local (右)コンテナ
    ports:
      # - 3306:3306 # Mysqlのデフォルト
      - "5432:5432" #Postgresqlのデフォルト

volumes:
  db-volume:
